# Generated by Django 3.0.7 on 2021-08-25 10:54

from django.db import migrations, models
import django.db.models.deletion
import mail_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailer', models.CharField(max_length=128)),
                ('topic', models.CharField(blank=True, max_length=256)),
                ('text', models.TextField(blank=True)),
                ('date_time', models.DateTimeField()),
                ('uid', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mail_attachments/')),
                ('letter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter', to='mail_app.Letter')),
            ],
        ),
    ]
