# Generated by Django 3.0.7 on 2021-08-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0002_letter_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
