# Generated by Django 3.0.7 on 2021-09-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0004_auto_20210911_1620'),
        ('mail_app', '0002_auto_20210911_1105'),
    ]

    operations = [
    ]
