# Generated by Django 3.0.7 on 2020-08-28 21:00

import colorfield.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, unique=True)),
                ('topic', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'verbose_name': 'День',
                'verbose_name_plural': 'Дни',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('topic', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='calendar_app.Day')),
                ('event_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_info', to='calendar_app.Info')),
            ],
        ),
    ]
