# Generated by Django 3.0.7 on 2021-09-11 13:20

import colorfield.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Тип события', 'verbose_name_plural': 'Типы событий'},
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default=datetime.date.today, unique=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='day',
            name='topic',
            field=models.CharField(blank=True, max_length=256, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='calendar_app.Day', verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_info', to='calendar_app.Info', verbose_name='Тема события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время события'),
        ),
        migrations.AlterField(
            model_name='info',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='info',
            name='topic',
            field=models.CharField(blank=True, max_length=256, verbose_name='Тема'),
        ),
    ]
