# Generated by Django 3.0.7 on 2021-11-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_auto_20210911_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='topic',
        ),
    ]
