# Generated by Django 3.0.7 on 2020-09-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos_news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(related_name='tag', to='demos_news_app.Post'),
        ),
    ]
